version: '3'
services:
  
  redis-server:
    image: 'redis'

  mysql-app:
    image: 'mysql:5.7'
    environment: 
      MYSQL_ROOT_PASSWORD: password

  admin-db:
    image: phpmyadmin
    ports: 
      - "8080:80"
    environment: 
      MYSQL_ROOT_PASSWORD: password
      PMA_HOST: mysql-app

  node-app:
    build: .
    ports:
      - "4001:8081"
    restart: always