version: '3.9'

services: 

    db:
        image: 'mysql:5.7'
        environment: 
            MYSQL_ROOT_PASSWORD: 'password'
            MYSQL_DATABASE: 'exo3'

    web:
        depends_on: 
            - db
        build: 
            dockerfile: Dockerfile
            context: .
        ports: 
            - 5000:5000
        restart: always