#cloud-config
package_upgrade: true
packages:
  - nginx
  - nodejs
  - npm
  - git
write_files:
  - owner: www-data:www-data
    path: /etc/nginx/sites-available/default
    content: |
      server {
        listen 80;
        location / {
          proxy_pass http://localhost:1337;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection keep-alive;
          proxy_set_header X-Forwarded-For $remote_addr;
          proxy_set_header Host $host;
          proxy_cache_bypass $http_upgrade;
        }
      }
runcmd:
  - cd "/home/vagrant"
  - git clone https://github.com/Azure-Samples/nodejs-docs-hello-world
  - cd "/home/vagrant/nodejs-docs-hello-world"
  - npm install pm2
  - ./node_modules/pm2/bin/pm2 start -f index.js
  - service nginx restart
