# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV["LC_ALL"] = "fr_FR.UTF-8"

Vagrant.configure('2') do |config|
  config.vm.box = 'debian/buster64'
  
    config.vm.network 'public_network', ip: "192.168.0.42"
  
  config.vm.define 'ssh-client' do |machine|
    machine.vm.hostname = 'ssh-client'


  config.vm.provider 'virtualbox' do |vb|
    vb.memory = '2048'
  end
  end
	
  config.vm.provision "shell", path: "provision.sh"
end