# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
	config.vm.box = "debian/buster64"			
	config.vm.box_check_update = false
	
	# Iterating the loop for three times
	(1..1).each do |i|
		# Defining VM properties
		 config.vm.define "poste_dev_#{i}" do |node|
            node.vm.hostname = "postedev#{i}"		
			node.vm.network 'public_network', ip: "192.168.1.#{i}"
            node.vm.provider "virtualbox" do |vb|
				vb.gui = false
				vb.memory = 4096
				vb.cpus = 4
            end
			node.vm.provision "shell", path: "provision_poste-dev.sh"
        end
	end
end