Vagrant.configure("2") do |config|

	config.vm.box = "ubuntu/bionic64"
  
	config.vm.provider "virtualbox" do |vb|
		vb.memory = 4096
		vb.cpus = 4
	end

	config.vm.network "private_network", ip: "192.168.33.20"
	# config.vm.network "public_network", ip: "192.168.1.35"
  
	config.vm.synced_folder 'shared', '/home/shared'
	config.vm.provision "shell", path: "provision.sh"

end