Vagrant.configure("2") do |config|

	config.vm.box = "ubuntu/bionic64"
  
	config.vm.provider "virtualbox" do |vb|
		vb.memory = 2048
		vb.cpus = 1
		vb.name = "terraform"
	end

	config.vm.network "private_network", ip: "192.168.33.200"
	
	config.vm.synced_folder 'shared', '/home/shared'
	config.vm.provision "shell", path: "provision.sh"
	config.vm.hostname = "terraform"
end