# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
  config.vm.box = 'rogeriozambon/python'

  config.vm.network 'forwarded_port',
                    guest: 80,
                    host: 8880

  config.vm.provider 'virtualbox' do |vb|
    vb.memory = '2048'
  end
	
  config.vm.provision "shell", path: "provision.sh"
end