Vagrant.configure("2") do |config|
config.vm.box = "ubuntu/bionic64"

	config.vm.provider "virtualbox" do |vb|
		vb.memory = 1024
		vb.cpus = 1
		vb.name = "target1"
	end

	config.vm.network "private_network", ip: "192.168.33.100"
	config.vm.hostname = "target1"

end