#!/bin/sh

alias RM='f(){ ./rm.sh $1 }; f'

alias RESTORE='g(){ ./restore.sh $1 }; g'

CORBEILLE=/home/vagrant/corbeille/

alias TRASH='ls $CORBEILLE'

if [ ! -f "$CORBEILLE" ]
then
	mkdir $CORBEILLE
fi