# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV["LC_ALL"] = "fr_FR.UTF-8"

Vagrant.configure('2') do |config|
  config.vm.box = 'debian/buster64'

  config.vm.network 'forwarded_port',
                    guest: 80,
                    host: 8880,
                    host_ip: '127.0.0.1'

  config.vm.provider 'virtualbox' do |vb|
    vb.memory = '2048'
  end
	
  config.vm.provision "shell", path: "provision.sh"
end