# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV["LC_ALL"] = "fr_FR.UTF-8"

Vagrant.configure('2') do |config|
  config.vm.box = 'debian/buster64'

  config.vm.network 'forwarded_port',
                    guest: 80,
                    host: 8880,
                    host_ip: '127.0.0.1'

  config.vm.provider 'virtualbox' do |vb|
    vb.gui = true
    vb.memory = '2048'
	vb.customize ["modifyvm", :id, "--vram", "12"]
  end
	
  config.vm.provision "shell", path: "provision.sh"

  #config.vm.provision 'shell', inline: <<-SHELL
    #apt-get update
	#apt-get install -y vim
	#apt-get install -y tldr
	#apt-get install -y shellcheck
    #apt-get install -y apache2
	#apt-get install -y php7.3
	#apt-get install -y libapache2-mod-php7.3
	#apt-get install -y kde-plasma-desktop
	#echo "PGh0bWw+PGhlYWQ+PG1ldGEgY2hhcnNldD0idXRmLTgiLz48L2hlYWQ+PGJvZHk+PGgxPkMnZXN0IGJvbiwgw6dhIGZvbmN0aW9ubmUgITwvaDE+PC9ib2R5PjwvaHRtbD4K" | base64 -d > /var/www/html/index.html
  #SHELL
end