# -*- mode: ruby -*-
# vi: set ft=ruby :

machines=[
  {
    :hostname => "serverWeb",
    :box => "debian/buster64",
    :ram => 2048,
    :cpu => 2,
	:gui => false,
	:provision => "provision_server_web.sh"
  }
]

Vagrant.configure(2) do |config|
    machines.each do |machine|
        config.vm.define machine[:hostname] do |node|
            node.vm.box = machine[:box]			
			node.vm.box_check_update = false
            node.vm.hostname = machine[:hostname]
			node.vm.synced_folder "share/", "/home/vagrant"
			
			  node.vm.network 'forwarded_port',
                    guest: 80,
                    host: 8880,
                    host_ip: '127.0.0.1'
			
            # node.vm.network "private_network", ip: machine[:ip]
            node.vm.provider "virtualbox" do |vb|
				vb.gui = machine[:gui]
				vb.memory = machine[:ram]
				vb.cpus = machine[:cpu]
            end
			node.vm.provision "shell", path: machine[:provision]
        end
    end
end